server:
  port: 20001

management:
  endpoints:
    web:
      exposure:
        include: ["health", "prometheus"]

logging:
  config: 'classpath:config/logback-spring.xml'
  level:
    root: DEBUG
    org.springframework.web: DEBUG