server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: ["health", "prometheus"]

logging:
  config: 'classpath:config/logback-spring.xml'
  level:
    root: INFO
    org.springframework.web: INFO